### ISSUE TITLE
Search Icon Cosmetic Change

### ISSUE THREAD

**Issue by calarada** [AmirKhamesy/adoreptile#10]
When clicking the magnifying glass icon to search, the rectangle that pops up to type into is outlined in a weird blue colour that looks out of place

https://github.com/user-attachments/assets/a59e245d-ca11-4ce3-bf52-2aee43aa2135

**Comment by AmirKhamesy** [comment]
fixed with #15b9abb89c875792170707739d00ccbddc31006b
